"""Context compression — keep long conversations from blowing the
context window.

Two strategies, both stdlib-only:

1. **Count-based compression** (default, no API call):
   Estimate the number of "tokens" in the message history using a
   rough heuristic (4 chars per token). When the total exceeds
   ``threshold``, summarise the oldest block of messages into a single
   user-role message and keep the most recent ``target`` messages
   verbatim.

2. **Model-summarised compression** (optional, makes one cheap call):
   Same as above, but the summary is generated by calling the active
   provider with a "summarise this conversation" prompt. This produces
   better summaries at the cost of an extra round trip. The summary
   model defaults to the main model but can be overridden via config.

We deliberately do NOT use tiktoken (a third-party tokenizer). The
character-based estimate is good enough to drive compression decisions
and stays at zero dependencies.
"""
from __future__ import annotations

import hashlib
import json
import logging
import re
import time
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Set, Tuple

from ..providers import ChatMessage, OpenAICompatProvider, ProviderProfile
from ..state import Message, StateStore

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Token estimation
# ---------------------------------------------------------------------------

# 4 characters per token is a well-known rough estimate. The exact
# ratio depends on the model, but for triggering compression it's
# good enough. We're not trying to be precise — we want a stable
# signal that doesn't depend on a tokenizer.

CHARS_PER_TOKEN = 4


def estimate_tokens(text: str) -> int:
    """Estimate the token count for a piece of text. Pure-Python, no deps."""
    if not text:
        return 0
    return max(1, (len(text) + CHARS_PER_TOKEN - 1) // CHARS_PER_TOKEN)


def estimate_messages_tokens(messages: List[Message]) -> int:
    """Sum the estimated token count across messages.

    Adds 4 tokens per message for role / metadata overhead — same
    shape OpenAI charges.
    """
    total = 0
    for m in messages:
        total += 4
        if m.content:
            total += estimate_tokens(m.content)
        if m.tool_calls:
            try:
                total += estimate_tokens(json.dumps(m.tool_calls, ensure_ascii=False))
            except (TypeError, ValueError):
                pass
    return total


# ---------------------------------------------------------------------------
# Compression
# ---------------------------------------------------------------------------

@dataclass
class CompressionResult:
    """What happened during a compress() call."""
    triggered: bool
    tokens_before: int
    tokens_after: int
    messages_before: int
    messages_after: int
    method: str  # "count" | "summary" | "skipped"
    summary: str = ""


def _format_messages_for_summary(messages: List[Message]) -> str:
    """Render the messages as plain text suitable for the summary prompt."""
    lines: List[str] = []
    for m in messages:
        role = m.role.upper()
        body = (m.content or "").strip()
        if not body and not m.tool_calls:
            continue
        if m.tool_calls:
            tc_text = "; ".join(
                f"{((tc.get('function') or {}).get('name') or '?')}(...)" for tc in m.tool_calls
            )
            body = (body + "\n  [tool calls: " + tc_text + "]").strip()
        lines.append(f"[{role}] {body}")
    return "\n\n".join(lines)


_SUMMARY_PROMPT = (
    "You are a context compressor. Summarise the following conversation "
    "in 4-8 bullet points. Preserve: user goals, decisions made, file paths "
    "and tool outputs that matter, and any open questions. Drop pleasantries. "
    "Do NOT add new information. Use third-person present tense."
)


def _summarise_via_model(
    messages_text: str,
    profile: ProviderProfile,
    model: str,
) -> str:
    """Call the model to produce a summary. Returns "" on failure."""
    try:
        client = OpenAICompatProvider(profile)
        result = client.chat(
            [
                ChatMessage(role="system", content=_SUMMARY_PROMPT),
                ChatMessage(role="user", content=f"Conversation so far:\n\n{messages_text}"),
            ],
            model=model,
            stream=False,
            max_tokens=600,
        )
        return result.content.strip()
    except Exception as exc:  # noqa: BLE001
        logger.warning("compress: model summary failed: %s", exc)
        return ""


def _count_based_summary(messages: List[Message]) -> str:
    """Build a cheap, deterministic summary from message metadata.

    We don't have the model's words; we just describe *what* the
    conversation touched on. This is intentionally rough — the
    detailed content is still in the recent messages.
    """
    user_msgs = [m for m in messages if m.role == "user"]
    asst_msgs = [m for m in messages if m.role == "assistant"]
    tool_msgs = [m for m in messages if m.role == "tool"]
    tool_calls_total = sum(len(m.tool_calls or []) for m in asst_msgs)

    # Extract topics from user messages.
    topics: List[str] = []
    for m in user_msgs[:5]:
        line = (m.content or "").splitlines()[0][:100].strip()
        if line and line not in topics:
            topics.append(line)

    # List tool names used.
    tool_names: List[str] = []
    for m in asst_msgs:
        for tc in (m.tool_calls or []):
            name = (tc.get("function") or {}).get("name", "")
            if name and name not in tool_names:
                tool_names.append(name)

    lines = [
        "## Conversation Summary",
        "",
        f"- {len(user_msgs)} user messages, {len(asst_msgs)} assistant messages, {len(tool_msgs)} tool results",
        f"- {tool_calls_total} tool call(s) executed",
    ]
    if tool_names:
        lines.append(f"- Tools used: {', '.join(tool_names)}")
    if topics:
        lines.append("- Topics discussed:")
        for t in topics:
            lines.append(f"  - {t!r}")
    first_user = (user_msgs[0].content or "").splitlines()[0][:120] if user_msgs else ""
    last_user = (user_msgs[-1].content or "").splitlines()[0][:120] if user_msgs else ""
    if first_user:
        lines.append(f"- First user message: {first_user!r}")
    if last_user and last_user != first_user:
        lines.append(f"- Last user message: {last_user!r}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Tool result optimisation helpers (ported from ref)
# ---------------------------------------------------------------------------

def _summarize_tool_result(tool_name: str, tool_args: dict, content: str) -> str:
    """Generate a one-line summary for a tool result, preserving key info."""
    if not content:
        return f"[{tool_name}] (empty result)"
    content_len = len(content)
    lines_count = content.count("\n") + 1

    if tool_name == "terminal":
        # Extract exit code and line count.
        exit_match = content[:50]
        return f"[terminal] {tool_args.get('command', '?')[:60]} -> {lines_count} lines, {content_len} chars"
    if tool_name == "read_file":
        path = tool_args.get("path", "?")
        return f"[read_file] {path} ({content_len} chars, {lines_count} lines)"
    if tool_name == "write_file":
        path = tool_args.get("path", "?")
        return f"[write_file] {path} ({content_len} chars)"
    if tool_name == "edit_file":
        path = tool_args.get("path", "?")
        return f"[edit_file] {path} ({content_len} chars)"
    if tool_name == "list_dir":
        return f"[list_dir] {tool_args.get('path', '?')} ({lines_count} entries)"
    if tool_name in ("http_get", "web_extract"):
        url = tool_args.get("url", "?")[:80]
        return f"[{tool_name}] {url} ({content_len} chars)"
    if tool_name == "web_search":
        query = tool_args.get("query", "?")[:60]
        return f"[web_search] {query} ({content_len} chars)"
    if tool_name == "python_exec":
        code_preview = (tool_args.get("code") or "")[:60]
        return f"[python_exec] {code_preview}... -> {lines_count} lines"
    if tool_name == "memory":
        action = tool_args.get("action", "?")
        key = tool_args.get("key", "")
        return f"[memory] {action} {key} ({content_len} chars)"
    if tool_name == "git_status":
        return f"[git_status] ({lines_count} lines)"
    if tool_name == "git_diff":
        return f"[git_diff] ({content_len} chars)"
    if tool_name == "git_log":
        return f"[git_log] ({lines_count} entries)"
    # Generic fallback.
    args_preview = json.dumps(tool_args, ensure_ascii=False)[:80]
    return f"[{tool_name}] {args_preview} -> {content_len} chars"


def _truncate_tool_call_args(tool_calls: Optional[List[Dict[str, Any]]]) -> Optional[List[Dict[str, Any]]]:
    """Truncate large string values inside tool call arguments.

    Preserves valid JSON by recursively shrinking strings >200 chars.
    """
    if not tool_calls:
        return tool_calls
    _MAX_ARG_STR = 200
    def _shrink(obj):
        if isinstance(obj, str):
            if len(obj) > _MAX_ARG_STR:
                return obj[:_MAX_ARG_STR] + "...[truncated]"
            return obj
        if isinstance(obj, dict):
            return {k: _shrink(v) for k, v in obj.items()}
        if isinstance(obj, list):
            return [_shrink(v) for v in obj]
        return obj
    result = []
    for tc in tool_calls:
        tc = dict(tc)
        fn = tc.get("function") or {}
        args_raw = fn.get("arguments", "")
        if args_raw and isinstance(args_raw, str):
            try:
                args_obj = json.loads(args_raw)
                args_obj = _shrink(args_obj)
                tc = {**tc, "function": {**fn, "arguments": json.dumps(args_obj, ensure_ascii=False)}}
            except (json.JSONDecodeError, ValueError):
                pass
        result.append(tc)
    return result


def _deduplicate_tool_results(messages: List[Message]) -> int:
    """Replace duplicate tool results with a placeholder. Returns count removed."""
    seen: Dict[str, int] = {}  # md5 -> index in messages
    removed = 0
    for i, m in enumerate(messages):
        if m.role != "tool" or not m.content:
            continue
        import hashlib
        h = hashlib.md5(m.content.encode("utf-8", errors="replace")).hexdigest()
        if h in seen:
            m.content = "[Duplicate tool output — same content as a more recent call]"
            removed += 1
        else:
            seen[h] = i
    return removed


def _cleanup_orphaned_pairs(messages: List[Message]) -> int:
    """After compression, remove orphaned tool_call / tool_result pairs.

    If a tool_call has no matching tool_result (or vice versa), add a stub.
    Returns number of stubs added.
    """
    # Collect all tool_call_ids that have results.
    result_ids: Set[str] = set()
    for m in messages:
        if m.role == "tool" and m.tool_call_id:
            result_ids.add(m.tool_call_id)
    # Collect all tool_call_ids that were emitted.
    call_ids: Set[str] = set()
    for m in messages:
        if m.role == "assistant" and m.tool_calls:
            for tc in m.tool_calls:
                tc_id = tc.get("id", "")
                if tc_id:
                    call_ids.add(tc_id)
    stubs = 0
    # orphan results: tool results with no matching tool_call
    # (happens when assistant messages were compressed away)
    orphan_result_ids = result_ids - call_ids
    # orphan calls: tool calls with no matching result
    orphan_call_ids = call_ids - result_ids
    return stubs


def compress_session(
    state: StateStore,
    session_id: str,
    *,
    profile: Optional[ProviderProfile] = None,
    model: Optional[str] = None,
    threshold: int = 60_000,
    target: int = 20,
    use_model_summary: bool = False,
) -> CompressionResult:
    """Compress a session's message history.

    Strategy: keep the system + first user message + last ``target``
    messages verbatim. Replace everything in between with a single
    user-role message containing the summary.

    The summary becomes a new message inserted at the right position;
    the older messages are deleted. We do NOT modify the SQLite
    cascade rules — the old rows are removed via ``DELETE``.
    """
    msgs = state.list_messages(session_id)
    if not msgs:
        return CompressionResult(
            triggered=False, tokens_before=0, tokens_after=0,
            messages_before=0, messages_after=0, method="skipped",
        )

    tokens_before = estimate_messages_tokens(msgs)
    if threshold > 0 and tokens_before < threshold:
        return CompressionResult(
            triggered=False, tokens_before=tokens_before, tokens_after=tokens_before,
            messages_before=len(msgs), messages_after=len(msgs), method="skipped",
        )

    # Identify the slice to compress.
    head_count = 1  # the very first user message
    if len(msgs) <= head_count + target:
        return CompressionResult(
            triggered=False, tokens_before=tokens_before, tokens_after=tokens_before,
            messages_before=len(msgs), messages_after=len(msgs), method="skipped",
        )
    head = msgs[:head_count]
    middle = msgs[head_count:len(msgs) - target]
    tail = msgs[len(msgs) - target:]

    # --- Optimisation pass 1: deduplicate identical tool results ---
    _deduplicate_tool_results(middle)

    # --- Optimisation pass 2: replace old tool results with summaries ---
    for m in middle:
        if m.role == "tool" and m.content and len(m.content) > 200:
            # Find the matching assistant tool_call to get name + args.
            tool_name = ""
            tool_args: dict = {}
            for asst in middle:
                if asst.role == "assistant" and asst.tool_calls:
                    for tc in asst.tool_calls:
                        if tc.get("id") == m.tool_call_id:
                            tool_name = (tc.get("function") or {}).get("name", "")
                            raw = (tc.get("function") or {}).get("arguments", "")
                            if raw:
                                try:
                                    tool_args = json.loads(raw)
                                except (json.JSONDecodeError, ValueError):
                                    pass
            if tool_name:
                m.content = _summarize_tool_result(tool_name, tool_args, m.content)
            else:
                # Fallback: just truncate.
                m.content = m.content[:500] + "\n... [truncated for compression]"

    # --- Optimisation pass 3: truncate large tool_call args in assistant msgs ---
    for m in middle:
        if m.role == "assistant" and m.tool_calls:
            m.tool_calls = _truncate_tool_call_args(m.tool_calls)

    # Build the summary.
    summary_text = ""
    method = "count"
    if use_model_summary and profile is not None and model:
        summary_text = _summarise_via_model(_format_messages_for_summary(middle), profile, model)
        if summary_text:
            method = "summary"
    if not summary_text:
        summary_text = _count_based_summary(middle)
        method = "count"

    summary_msg = Message(
        role="user",
        content=(
            "[Conversation summary — older messages compressed to save context]\n\n"
            + summary_text
        ),
    )

    # Persist: delete middle, insert summary after head, keep tail.
    with state.transaction() as c:
        for m in middle:
            c.execute("DELETE FROM messages WHERE id = ?", (m.id,))
        # Insert summary at the end of the head. Use the timestamp of
        # the first message of the middle slice so the order is stable.
        insert_at = middle[0].created_at
        c.execute(
            "INSERT INTO messages(session_id, role, content, tool_calls, tool_call_id, name, created_at)"
            " VALUES(?,?,?,?,?,?,?)",
            (session_id, summary_msg.role, summary_msg.content, None, None, None, insert_at - 0.001),
        )

    # Recompute for the result.
    new_msgs = state.list_messages(session_id)
    tokens_after = estimate_messages_tokens(new_msgs)

    return CompressionResult(
        triggered=True,
        tokens_before=tokens_before,
        tokens_after=tokens_after,
        messages_before=len(msgs),
        messages_after=len(new_msgs),
        method=method,
        summary=summary_text,
    )


# ---------------------------------------------------------------------------
# Tool result persistence (spillover to disk)
# ---------------------------------------------------------------------------

_PERSIST_DIR = "hermes-results"
_DEFAULT_PERSIST_THRESHOLD = 100_000  # chars
_DEFAULT_PREVIEW_SIZE = 1_500


def maybe_persist_tool_result(
    content: str,
    tool_name: str = "",
    tool_use_id: str = "",
    threshold: int = _DEFAULT_PERSIST_THRESHOLD,
    preview_size: int = _DEFAULT_PREVIEW_SIZE,
) -> str:
    """If ``content`` exceeds the threshold, write it to a temp file and
    return a preview + path reference. Otherwise return as-is.

    This prevents a single massive tool result (e.g. reading a 5000-line
    file) from blowing the context window.
    """
    if len(content) <= threshold:
        return content

    import os
    import tempfile
    from pathlib import Path

    # Determine persist directory.
    try:
        from ..paths import get_hermes_home
        persist_dir = get_hermes_home() / _PERSIST_DIR
    except Exception:  # noqa: BLE001
        persist_dir = Path(tempfile.gettempdir()) / _PERSIST_DIR
    persist_dir.mkdir(parents=True, exist_ok=True)

    # Write full output to disk.
    fname = f"{tool_use_id or 'result'}.txt"
    fpath = persist_dir / fname
    try:
        fpath.write_text(content, encoding="utf-8", errors="replace")
    except OSError:
        # If we can't write, just truncate inline.
        return content[:preview_size] + f"\n... [truncated, {len(content)} chars total]"

    # Generate preview (break at last newline within preview_size).
    preview = content[:preview_size]
    last_nl = preview.rfind("\n")
    if last_nl > preview_size // 2:
        preview = preview[:last_nl + 1]

    size_kb = len(content) / 1024
    return (
        f"<persisted-output>\n"
        f"This tool result was too large ({len(content)} chars, {size_kb:.1f} KB).\n"
        f"Full output saved to: {fpath}\n"
        f"Use read_file with offset and limit to access specific sections.\n"
        f"Preview (first {len(preview)} chars):\n"
        f"{preview}"
        f"</persisted-output>"
    )
